name: Spell checking
on: push

jobs:
  build:
    name: Spell checker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
    - uses: ./action-spelling
      env:
        bucket: https://raw.githubusercontent.com/jsoref/spelling-action
        project: spelling-data
